version: '3'
services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5434:5432
  product-postgres:
    image: product-postgres:0.1
    depends_on:
      - postgres-db
    container_name: product-postgres
    ports:
      - 9005:9005
    build: .